name: vc_vmp
channels:
  - conda-forge
  - defaults
  - pytorch
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10.16
  - numpy=1.26.4
  - pandas
  - h5py
  - spacy
  - nltk
  - pytorch
  - torchvision
  - torchaudio
  - tensorboardx
  - jupyter
  - opencv
  - notebook
  - pycocoevalcap
  - pip=25.0
